### ISSUE TITLE
https://hg.mozilla.org/mozilla-central/rev/2777ec78a2b5 redirect issue

### ISSUE THREAD

**Issue by octoploid** [RequestPolicy/requestpolicy#318] opened 2012-07-03 18:25 UTC
Since commit https://hg.mozilla.org/mozilla-central/rev/2777ec78a2b5 
when you (manually) enter a new URL on a existing page RequestPolicy always
asks "This webpage has asked to redirect to (new URL)  Allow, Deny, More...". 
(For example open "www.google.com" and then enter "www.bing.com" in the bar and press enter)

**Comment by devd** [comment] 2012-07-03 18:55
This is weird: none of the arguments to the shouldLoad call should have changed, other than an extra argument that request policy doesn't know about. @Justin: any idea on what is happening here?

**Comment by nadR** [comment] 2012-07-04 12:52
I can confirm this issue, also, when trying to whitelist the destination site through the preferences the redirect pop-up still shows itself.

**Comment by JagsDesai** [comment] 2012-07-08 00:13
Just came in here to report this and I see that the issue has already been reported. I'm using RequestPolicy (with Firefox nightly) for a while and this has started since last week or so.

**Comment by devd** [comment] 2012-07-09 01:14
Yup, this is being tracked upstream at https://bugzilla.mozilla.org/show_bug.cgi?id=771736

**Comment by jsamuel** [comment] 2012-07-09 23:18
Hey Dev. Awesome stuff moving CSP forward.

How things used to work was that when RequestPolicy saw aRequestOrigin was moz-nullprincipal, it would use aContext.contentDocument.documentURI as the referrer. That was just a hack to deal with the fact that aRequestOrigin was moz-nullprincipal sometimes when there really should have been an actual referrer there. For URLs entered in the location bar, aRequestOrigin used to be a chrome:// URI (specifically, chrome://browser/content/browser.xul). 

As best as I can tell with Fx 16, possibly not completely due to https://bugzil.la/767134, I can now always count on aRequestOrigin being the actual referrer and it will be moz-nullprincipal only when there really isn't a referrer. So, RP's moz-nullprincipal/aContext.contentDocument hack now causes problems because aRequestOrigin is a moz-nullprincipal URI instead of a chrome:// URI when a URL is entered in the location bar.

If I'm wrong about the fact that aRequestOrigin will now only be a moz-nullprincipal URI when there truly isn't a referrer, then my fix for this ticket may introduce RP bypasses. That would certainly be a bummer.

**Closed as completed by jsamuel** 2012-07-09 23:18 UTC
Labels: bug report

**Comment by jsamuel** [comment] 2012-07-09 23:57
And thanks, Trippelsdorf, for noticing and reporting this as quickly as you did.
